### ISSUE TITLE
Upload images not shown

### ISSUE THREAD

**Issue by shinokada** [dwijitsolutions/laraadmin#10]
You need to change line 249 in resources/views/la/uploads/index.blade.php to following. I don't know why you had `?s=130` at the end. 

        image = '<img src="'+bsurl+'/files/'+upload.hash+'/'+upload.name+'">';

**Comment by gdbhosale** [comment]
Thanks shinokada,

parameter s is for size of thumbnail.
If s is not passed original image will be returned.

Regards,
