### ISSUE TITLE
Deafult date in custom date field is "2001-01-01" should be now()

### ISSUE THREAD

**Issue by netinteractive** [dwijitsolutions/laraadmin#102]
as titled:)

**Comment by gdbhosale** [comment]
This needs to be done.

**Comment by madhavikhatal** [comment]
Default Date Value not working in MySQL. It goes to NULL

**Comment by gdbhosale** [comment]
We cannot have current date as default value for Date type in MySQL.

Datetime works very well with now().

Closing the issue.
