### ISSUE TITLE
Failed to delete a module before generating it

### ISSUE THREAD

**Issue by rxstriker** [dwijitsolutions/laraadmin#104]
As title says.
`
SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'aliartalentos_laraadmin_crm.reports' (SQL: drop table 'reports')
`

**Comment by gdbhosale** [comment]
Need to be fixed

**Comment by gdbhosale** [comment]
Fixed...

ModuleController.php:186
```
// Delete Table
if (Schema::hasTable($module->name_db)) {
	Schema::drop($module->name_db);
}
```
Best Regards
