### ISSUE TITLE
Display image in list

### ISSUE THREAD

**Issue by vangelis183** [dwijitsolutions/laraadmin#106]
Is there a possibility to display the image in the list instead of id if the column type is image?
Same for multiple selection.

**Comment by gdbhosale** [comment]
Hi @vangelis183,

You need to customise these changes manually after CRUDSs are generated.

Check organisation Module for that. It takes Image as column. You can go these changes from Controller in dt_ajax methods.

You have to do multiple selection by your own. You can check datatables for same.
https://datatables.net/examples/api/select_row.html

Regards,
