### ISSUE TITLE
Deleted Records gets displayed

### ISSUE THREAD

**Issue by richardkeep** [dwijitsolutions/laraadmin#11]
I have noticed another bug where a deleted record is still listed on the index page. When you click the Edit/Delete button, the system throws an error because `deleted_at` is `NOT NULL` therefore the record cannot be accessed. I am aware the models use `Illuminate\Database\Eloquent\SoftDeletes`.

I think this is because you are using Database Querys rather that Eloquent to fetch data for Datatables display.

**Comment by gdbhosale** [comment]
I have added soft delete very recently. Try using fresh installation.
It will definitely work. Let me know once resolved.

Regards,

**Comment by richardkeep** [comment]
I have done `composer update` and now am running the latest version 1.0.14, but the problem still persists. Datatables is still fetching the deleted record to the index page.

**Comment by kristo-j** [comment]
Deleting only changes the "deleted_at" column. You can make the query only fetch values where the column value is null.

**Comment by gdbhosale** [comment]
This problem is resolved in latest version of LaraAdmin.
DB::table function includes deleted items.
We used - ->whereNull('deleted_at');
