### ISSUE TITLE
One to Many Relationship

### ISSUE THREAD

**Issue by Rav23** [dwijitsolutions/laraadmin#111]
Hi there,
I simply copied the role_users example for implementing many to many relationships. But how do I go about adding just the id of a different table to a module generated by this awesome package?

**Comment by gdbhosale** [comment]
This has to be done manually.

Package only configures foreign key automatically while migration.
But belongs_to methods has to be created manually

Regards,

**Comment by gdbhosale** [comment]
Check how https://github.com/laraadmin/laraadmin-dev/blob/master/app/Models/Upload.php
has linked to user table. You can do like it manually. Closing the issue...
