### ISSUE TITLE
How to update laraadmin 

### ISSUE THREAD

**Issue by azarzaza** [dwijitsolutions/laraadmin#114]
Is there any command for update laraadmin I have used la:update doesn't work

**Comment by slozano95** [comment]
@azarzaza you might use git clone inside /vendor/dwij to clone master repo

**Comment by sagarkoshti1990** [comment]
Use this documentation: http://laraadmin.com/docs/1.0/upgrades

**Comment by azarzaza** [comment]
I was use the documentation when upgrade they make new files and some of my project files are deleted I am using git on my local machine I am working with project in local I have lost my some code plz how to update the new change in my project without data loss

**Comment by gdbhosale** [comment]
You should use Visual Studio Code Editor to do so. It properly shows
deleted files and manipulated file. It becomes easy to differentiate. Try
that. If you are using git and commited your changes before upgrade. No
data will be lost. You can simply undo deletion of old files which are
important. In new LaraAdmin we have moved the Models in app/Models folder
except 3 - Users, Roles, Permissions. You should move your old Models
inside that folder and change package path in them as well as from
references.

Regards
