### ISSUE TITLE
Can't install Laraadmin.

### ISSUE THREAD

**Issue by vanloc0301** [dwijitsolutions/laraadmin#12]
I read document at here:

http://laraadmin.com/documentation

OS: Windows 7.

I installed composer. I clone Laraadmin to local machine and `cd laraadmin`.

Tried with command: `composer require dwij/laraadmin`

It not any happen, I can't run `php artisan` (Could not open input file: artisan), not any folder I usually saw in 1 project using laravel.
I must copy manually `config, storage, bootstrap, .env, artisan` from `laravel` source into folder `laraadmin`.

So, I add this row: `Dwij\Laraadmin\LAProvider::class` into `config/app.php` folder.

Tried with installer command :

`php artisan la:install`

It throws error like:

> Class 'Illuminate\Foundation\Application' not found in C:\wamp64\www\l araadmin\src\bootstrap\app.php on line 14

At src\bootstrap\app.php line 14 is: 

```
$app = new Illuminate\Foundation\Application(
    realpath(__DIR__.'/../')
);
```

**Comment by gdbhosale** [comment]
Hello @vanloc0301,

Please understand Laravel framework first and then try the LaraAdmin.

If you move the bootstrap and other folders, you can't run Artisan command.

Regards
