### ISSUE TITLE
user cannot delete 

### ISSUE THREAD

**Issue by azarzaza** [dwijitsolutions/laraadmin#121]
user cannot delete when role or department or permission deleted 
eg 
if i created role user then use this in employee module to create new employee name called user1 
and use the role user 
then i delete the empoyee user1 mean i cant be delete 

need restriction for deleting foreign  keys once foreign key is used foreign key record  cant be deleted

**Comment by gdbhosale** [comment]
You need to customise same in LaraAdmin package itself in order to change
default behaviour.

Chekc our extending doc on http://laraadmin.com/docs/1.0/extending

Regards,
