### ISSUE TITLE
Cannot open Menu, Modules Manager

### ISSUE THREAD

**Issue by haidang** [dwijitsolutions/laraadmin#122]
After install, I cannot go to Menu and Modules Manger, please suggest me. Below is error:

> FatalErrorException in MenuController.php line 184:
> Cannot redeclare class Dwij\Laraadmin\Controllers\MenuController
> in MenuController.php line 184

> ReflectionException in Route.php line 280:
> Class App\Http\Controllers\Dwij\Laraadmin\Controllers\ModuleController does not exist

**Comment by gdbhosale** [comment]
I don't know when you get this error, but there is problem in ModuleController namespace.
It should be `\Dwij\Laraadmin\Controllers\ModuleController`. There should be `\` before `Dwij`.
This avoid prepending of `App\Http\Controllers`.

Best Regards,
