### ISSUE TITLE
How to show picture in the list?

### ISSUE THREAD

**Issue by edwinhuish** [dwijitsolutions/laraadmin#126]
As the picture below, how to show picture in the list. No just number 1 or 0 ?
![image](https://cloud.githubusercontent.com/assets/5207925/20822248/0d070c7e-b884-11e6-875c-b86632ce91d4.png)

**Comment by gdbhosale** [comment]
Hi,

You should check this and understand the logic:
https://github.com/dwijitsolutions/laraadmin/blob/master/src/Installs/app/Controllers/LA/OrganizationsController.php

**function dtajax**:
```
if($fields_popup[$col] != null && $fields_popup[$col]->field_type_str == "Image") {
    if($data->data[$i][$j] != 0) {
        $img = \App\Models\Upload::find($data->data[$i][$j]);
        if(isset($img->name)) {
            $data->data[$i][$j] = '<img src="'.$img->path().'?s=50">';
        } else {
            $data->data[$i][$j] = "";
        }
    } else {
        $data->data[$i][$j] = "";
    }
}
```

This will surely work.

Best Regards,
