### ISSUE TITLE
Installing laradmin artisan shows rare chars 

### ISSUE THREAD

**Issue by FMunumel** [dwijitsolutions/laraadmin#127]
At the end of Installing the app with composer, artisan shows rare chars like:

...
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
[32mGenerating optimized class loader[39m

> php artisan key:generate
[32mApplication key [base64:D15QFVB7GzNiqVyZK5AmPSEy9QksXPJdTnxj+1e1Wog=] set successfully.[39m

Any idea?

**Comment by gdbhosale** [comment]
Hi @FMunumel

No Idea. But this may be because of your OS. This is not an error.
No Worries....

Closing the issue.

Best Regards,
