### ISSUE TITLE
how to Add and hide/remove column in employees

### ISSUE THREAD

**Issue by sanathpathiraja** [dwijitsolutions/laraadmin#128]
ex: Alternative Mobile.
I removed @la_display($module, 'mobile2'),
but it shows.

and how to add new column,
@la_input($module, 'xxxxx')

**Comment by gdbhosale** [comment]
Hi,

There are two blade directives. la_form which displays the complete form
and another is la_input list which is generally commneted.

Best regards,

**Comment by sanathpathiraja** [comment]
I need to know,
how to add new field 
and
how remove already field.

plz give me a example.

thanks
