### ISSUE TITLE
New created crud not showing

### ISSUE THREAD

**Issue by sanathpathiraja** [dwijitsolutions/laraadmin#129]
I created following this http://laraadmin.com/docs/1.0/migrations_cruds
but not showing in menu items. and route is not working.

getting "page not found"

plz help.

**Comment by gdbhosale** [comment]
Please Check Module and Module Field Permission for your Role.

You can check this in Module Manager or in Role View

**Comment by sanathpathiraja** [comment]
Ok. i gives Module Field Permission. now it's working. 
thanks
