### ISSUE TITLE
How to show profile picture.

### ISSUE THREAD

**Issue by sanathpathiraja** [dwijitsolutions/laraadmin#130]
I uploaded picture. and it's show employee table perfectly.
i added it user table too.
I need to show that profile picture in top bar.

So how to get into top bar. it's show number.

help me.

**Comment by gdbhosale** [comment]
Hi,

Check this document once. http://laraadmin.com/docs/1.0/uploads_manager

Check Data-table implementation on https://github.com/dwijitsolutions/laraadmin/blob/master/src/Installs/app/Controllers/LA/OrganizationsController.php

Best Regards,
