### ISSUE TITLE
Form unique field and website field default behavior problems

### ISSUE THREAD

**Issue by rxstriker** [dwijitsolutions/laraadmin#131]
Defining a model field to unique, doesn't allow null values in form says (even when DB allows null value and default value is null):
"This value exists in database."
A website field doesn't allow the default value "http://" says:
"Please enter a valid URL."

**Comment by gdbhosale** [comment]
Hi,

Corrected this in dev-master. Soon launching the stable release 1.1.
Please send wishlist if any...

Best Regards
