### ISSUE TITLE
Remove "admin" route

### ISSUE THREAD

**Issue by haidang** [dwijitsolutions/laraadmin#133]
Dear Sir,

I want remove "admin" route from my URL. I tried change confige "adminRoute=''" at config/laraadmin.php.

But I have error when I go to Modules:
Route [.modules.store] not defined. (View: E:\xampp\htdocs\laraadmincrm\resources\views\la\modules\index.blade.php)
Route [.la_configs.store] not defined. (View: E:\xampp\htdocs\laraadmincrm\resources\views\la\la_configs\index.blade.php)
Route [.la_menus.destroy] not defined. (View: E:\xampp\htdocs\laraadmincrm\resources\views\la\menus\index.blade.php)

Please suggest me!

**Comment by gdbhosale** [comment]
Hi,

This error you are getting because of blank admin url.
You need to customise the package as per your requirements and remove `config('laraadmin.adminRoute')`. Check our extending document here: http://laraadmin.com/docs/1.0/extending

Best Regards,
