### ISSUE TITLE
join tables

### ISSUE THREAD

**Issue by persianscript** [dwijitsolutions/laraadmin#135]
hello
how i can join fields between tables from module?

sample shop table

Schema::create('shops', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->unsigned()->index();
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
            $table->integer('categories_id')->unsigned();
            $table->foreign('categories_id')->references('id')->on('categories');
            $table->string('title');
            $table->string('description');
            $table->string('status');
            $table->string('address');
            $table->string('tel');
            $table->string('image');
            $table->string('email')->uniqe();
            $table->string('password');
            $table->string('balance');
            $table->rememberToken();

and my location table

Schema::create('locations', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('shops_id')->unsigned()->index();
            $table->foreign('shops_id')->references('id')->on('shops')->onDelete('cascade');
            $table->string('title');
            $table->string('price');
            $table->timestamps();
        });

**Comment by gdbhosale** [comment]
Hi @persianscript,

I hope you have got your answer.

You can use @locations as poup_values

This will create foreign key linking automatically.

Best Regards,
