### ISSUE TITLE
Number of shown entries is resetted by every reload

### ISSUE THREAD

**Issue by stephanbauer** [dwijitsolutions/laraadmin#163]
First of all, thank you for this very useful project! I used it for a CRM to handle Contracts an so on.

I generated differents of Modules. But in every index view, every reload of the page does reset the nuber of entries that are shown to default 10 (nr of items per page). I did not find the place, where to fix this. Isn't the chosen value stored to the current session? I want to change the default to 50 entries. In case of a changed value by the current user, the system should remember this setting.

![bildschirmfoto vom 2017-02-16 17-05-04](https://cloud.githubusercontent.com/assets/3224960/23029239/1a52f290-f46a-11e6-890a-c0236bbce3e5.png)

I'm looking forward for a little hint where to adjust this. Thanks!

**Comment by azarzaza** [comment]
check it on where ur generated view files and change the js script according to the entries 
refer
https://datatables.net/reference/option/pageLength

please check the view in resource folder

**Comment by stephanbauer** [comment]
Thank you very much for this fast answer! Fixed it!
