### ISSUE TITLE
Validator & minimum integer values

### ISSUE THREAD

**Issue by twoSeats** [dwijitsolutions/laraadmin#17]
Hi,

Is there a reason why the minimum allowed value for integer inputs is 0? [link](https://github.com/dwijitsolutions/laraadmin/blob/master/src/LAFormMaker.php#L298)

In my particular case I need to allow negative integers.
Could changing the number range be made developer modifiable through a variable in config perhaps?

**Comment by gdbhosale** [comment]
You can configure it in FormMaker Blade Directive.
Yet documentation is remaining to be created.

**Comment by twoSeats** [comment]
Please could you give me an example?

**Comment by mgazelle** [comment]
Find the following piece of code around line 331 in vendor/dwij/laraadmin/src/LAFormMaker.php

			```
case 'Integer':
				$out .= '<label for="'.$field_name.'">'.$label.$required_ast.' :</label>';
				
				unset($params['data-rule-maxlength']);
				if($default_val == null) {
					$default_val = $defaultvalue;
				}
				// Override the edit value
				if(isset($row) && isset($row->$field_name)) {
					$default_val = $row->$field_name;
				}
				$params['min'] = "0";
				$out .= Form::number($field_name, $default_val, $params);
				break;
```
Here you can change the $params['min'] = "0";

Hope this helps

**Comment by gdbhosale** [comment]
Sorry for fixing it late.

Resolved in latest commit.

Regards,
