### ISSUE TITLE
Package not competable with laravel 5.2

### ISSUE THREAD

**Issue by sunarc-rahul** [dwijitsolutions/laraadmin#18]
Hi,
I installed this on laravel 5.2. Now when I login to admin panel after few clicks a popup shows me an Ajax datatble error. and also I logging out in few minutes weather I am work9ng or not.
User module is showing error while creating a new user but employee module is working fine. Issue is in user controller. Client module is not available yet.
This package is good but no rbac/entrust are there if they are also added it would be great.  
![sc](https://cloud.githubusercontent.com/assets/21167066/17997430/2f9081a2-6b8c-11e6-805e-736c19a9bc3b.png)

**Comment by gdbhosale** [comment]
Dear @sunarc-rahul ,

Please send your laravel log as well as network response for data-table request.

This package is built on Laravel 5.2 only. So there is no any compatibility issues with 5.2.

Regards,

**Comment by sunarc-rahul** [comment]
My project is also working on laravel 5.2. I have this on my local server I will update about all these issues after deploying on live server.

**Comment by mitulmlakhani** [comment]
Clear Your Browser Cookie And Check OR move all public data into root folder and run directly instead of artisan serve this resolved my issue.
