### ISSUE TITLE
How to select current user?

### ISSUE THREAD

**Issue by elektragroup** [dwijitsolutions/laraadmin#217]
Hi Team,

I am doing laraadmin project, While insert a new job how to select current user?
Means i want to insert current user in new module field.
Attached screenshot please help.

![capture](https://user-images.githubusercontent.com/29836170/28677247-888aa216-730a-11e7-9f9d-c1d356376c6e.JPG)

**Comment by Martenvanurk** [comment]
When you go to the template, look for the 

@la_input(<module>, '<field_name>', Auth::user()->id)

Add the third parameter

**Comment by elektragroup** [comment]
Thanks. It's working

**Comment by gpedro** [comment]
please, close the issue! @elektragroup
