### ISSUE TITLE
php artisan la:crud ... -146 Table 'laradmin.la_menus' doesn't exist'

### ISSUE THREAD

**Issue by fishmad** [dwijitsolutions/laraadmin#22]
C:\OneDrive\xampp\htdocs\laradmin>php artisan la:migration Lizard
Model:     Lizard
Module:    Lizards
Table:     lizards
Migration: create_lizards_table

Creating migration...
Migration done: 2016_08_30_033742_create_lizards_table.php

C:\OneDrive\xampp\htdocs\laradmin>php artisan migrate
Migrated: 2016_08_30_033742_create_lizards_table

C:\OneDrive\xampp\htdocs\laradmin>php artisan la:crud lizards
Creating controller...
Creating model...
Creating views...
Appending routes...
Appending Menu...
Crud::handle exception: exception 'PDOException' with message 'SQLSTATE[42S02]:
Base table or view not found: 1146 Table 'laradmin.la_menus' doesn't exist' in C
:\OneDrive\xampp\htdocs\laradmin\vendor\laravel\framework\src\Illuminate\Databas
e\Connection.php:333

  [Exception]
  Unable to generate migration for lizards : SQLSTATE[42S02]: Base table or v
  iew not found: 1146 Table 'laradmin.la_menus' doesn't exist (SQL: select co
  unt(*) as aggregate from `la_menus` where `url` = lizards)

![image](https://cloud.githubusercontent.com/assets/12012101/18075430/0ea1639c-6eb8-11e6-8e76-e49ed1d8f928.png)

**Comment by fishmad** [comment]
No la_menus in database or a migration file exists..

![image](https://cloud.githubusercontent.com/assets/12012101/18075503/a912dce4-6eb8-11e6-97e8-6fefa7afb165.png)

**Comment by gdbhosale** [comment]
Hi @fishmad,

Please update the laraadmin to latest version and run `la:install` command again to get new changes.
Use git to track file changes in installation.

Best regards,
