### ISSUE TITLE
Laraadmin - Get Uploaded file location from Auth, users

### ISSUE THREAD

**Issue by masterbd** [dwijitsolutions/laraadmin#224]
Hello!
I would like to get uploaded file instead of Gravatar in header nav bar. With this code:
**notifs.blade.php**
`{{ Auth::user()->photo }}`
- I only get the id of uploaded photo

I see that I have to use this
```
use App\Models\Upload;
$img = Upload::find( Auth::user()->photo );
$img->path();
```
But I don't know where to insert it in order to get in my views the file path...
I found one question same as mine, but answer is not so clear. Same as: https://github.com/dwijitsolutions/laraadmin/issues/130

**Comment by bobbysiagian** [comment]
Hi Masterdb,

if you see admin_routes.php , you will find, 
/* ================== Access Uploaded Files ================== */
Route::get('files/{hash}/{name}', 'LA\UploadsController@get_file');

Routes above it means, the way to fetch the file is by using : 
{{ url(config('laraadmin.adminRoute') . '/files/yourHashInUploadsTable/yourNameInUploadsTable') }}

**Comment by masterbd** [comment]
Hello **bobbysiagian**,

1. How do I get **yourHashInUploadsTable** and **yourNameInUploadsTable**?
2. Where _Auth::user_ is defined? I'm not able to find class file because I would like to create a new method for this, but IDK where it's is.

**Comment by bobbysiagian** [comment]
Hello @masterbd 
The first thing is make sure that you're still using default tables+modules when Laraadmin installed. Never custom uploads table and uploads modules.

1. Simple, 
   App\Models\yourModel::find(uploadsID)->hash->first();
   App\Models\yourModel::find(uploadsID)->name->first();

2. call `Use Auth` below namespace , then you can use Auth::User();

use dd(Auth::User()); if you want to debug it.

**Comment by masterbd** [comment]
Solved. Thank you very much.
