### ISSUE TITLE
Error install: Please set Cache Driver to array in .env (Required for Ziz aco\Entrust)

### ISSUE THREAD

**Issue by vanloc0301** [dwijitsolutions/laraadmin#23]
I tried to install Laraadmin and receive error message like this:

![untitled](https://cloud.githubusercontent.com/assets/4168981/18418781/ff8c935e-7876-11e6-82e2-c4fe5c534bfa.png)

Before, I installed success Laraadmin. But at this time, I can't install.

I don't know a reason, I read other issues and see your package compatible with Laravel 5.2.

I checked with command at my project:

`php artisan --version`

The result is:

 `Laravel Framework version: 5.2.45.`

**Comment by slozano95** [comment]
@vanloc0301 as it says you should set the CACHE_DRIVER to arrayin .env file that will fix the error

**Comment by vanloc0301** [comment]
Do you mean like this?

At .env file:

`CACHE_DRIVER=array`

At config/cache.php:

`'default' => env('CACHE_DRIVER', 'array'),`

**Comment by slozano95** [comment]
@vanloc0301 .env should work

**Comment by vanloc0301** [comment]
With this setting. It not working with me.

You need update to Laravel latest version because I think it relative with Laravel version.

**Comment by gdbhosale** [comment]
Hi @vanloc0301,

I have tested the package with various settings and it works well with CACHE_DRIVER=array

I am closing this issues as of now.
Please provide the details of installation and version of various packages you use.

Thanks & Regards,
