### ISSUE TITLE
Error when php artisan la:install (Laravel 5.4)

### ISSUE THREAD

**Issue by naijab** [dwijitsolutions/laraadmin#231]
[Exception]
  LAInstall::handle Unable to install : file(/var/www/html/app/Http/routes.php): failed to open stream: No suc
  h file or directory

**Comment by bobbysiagian** [comment]
open your laravel logs,
it causes file permission. The permission should be 777. @naijab

**Comment by ruslan-gennadievich** [comment]
https://stackoverflow.com/questions/39313536/missing-routes-php-file-in-new-laravel-project

**Comment by bobbysiagian** [comment]
The first thing is Laraadmin still better using Laravel ver 5.2 👯‍♂️

**Comment by kabelo38** [comment]
Laravel 5.4 is not compatible with Laradmin

**Comment by Jakobud** [comment]
Yeah it tries to use the wrong routes file and also uses `Illuminate\Foundation\Auth\Access\AuthorizesResources;` which is not in 5.4 anymore.

Any word when LA is going to be 5.4 compatible?
