### ISSUE TITLE
Parse error: syntax error, unexpected '$module' 

### ISSUE THREAD

**Issue by zunky44** [dwijitsolutions/laraadmin#25]
Parse error: syntax error, unexpected '$module' (T_VARIABLE), expecting ',' or ';' (View: /var/www/abcd/resources/views/la/employees/index.blade.php)

**Comment by mgazelle** [comment]
Have you changed index.blade.php? Very strange if you installed new. Could you paste the trace stack?

**Comment by gdbhosale** [comment]
Please update latest version of LaraAdmin and run `la:install`.

Closing the issue as of now.

Regards,
