### ISSUE TITLE
The default value of Datetime date('Y-m-d h:i:s') doesnt shows current timestamp

### ISSUE THREAD

**Issue by smartankur4u** [dwijitsolutions/laraadmin#258]
The default value of a field is set as date('Y-m-d h:i:s'), yet it shows the time as of 1970 everytime. It should show the current timestamp.
![screenshot-2017-12-16 trackings listing - laraadmin 1 0](https://user-images.githubusercontent.com/22790328/34068916-04a1edda-e26b-11e7-8f02-dc307dd134f0.png)

**Comment by khalid-shah** [comment]
Hi,
Your date format should be d/m/Y 

Thanks.
