### ISSUE TITLE
Checkboxes not handled correctly

### ISSUE THREAD

**Issue by mgazelle** [dwijitsolutions/laraadmin#26]
Are as TINYINT not retrieved and not saved properly in the database. I had to use Radios instead for now

**Comment by mgazelle** [comment]
Please change processDBRow in Modules.php at line 782 to 

$row->{$field['colname']} = $request->{$field['colname']} ? 1 : 0;

This will fix saving checkboxes

**Comment by mgazelle** [comment]
A small update again:

    public static function processDBRow($module, $request, $row) {
        $ftypes = ModuleFieldTypes::getFTypes2();
        foreach ($module->fields as $field) {
            if(isset($request->{$field['colname']})) {
                switch ($ftypes[$field['field_type']]) {
                    case 'Checkbox':
                        #TODO: Bug fix
                        $row->{$field['colname']} = 1;
                        break;
                    case 'Date':
                        if($request->{$field['colname']} != "") {
                            $date = $request->{$field['colname']};
                            $d2 = date_parse_from_format("d/m/Y",$date);
                            $request->{$field['colname']} = date("Y-m-d", strtotime($d2['year']."-".$d2['month']."-".$d2['day']));
                        }
                        $row->{$field['colname']} = $request->{$field['colname']};
                        break;
                    case 'Datetime':
                        #TODO: Bug fix
                        if($request->{$field['colname']} != "") {
                            $date = $request->{$field['colname']};
                            $d2 = date_parse_from_format("d/m/Y h:i A",$date);
                            $request->{$field['colname']} = date("Y-m-d H:i:s", strtotime($d2['year']."-".$d2['month']."-".$d2['day']." ".substr($date, 11)));
                        }
                        $row->{$field['colname']} = $request->{$field['colname']};
                        break;
                    case 'Multiselect':
                        #TODO: Bug fix
                        $row->{$field['colname']} = json_encode($request->{$field['colname']});
                        break;
                    case 'Password':
                        $row->{$field['colname']} = bcrypt($request->{$field['colname']});
                        break;
                    case 'Taginput':
                        #TODO: Bug fix
                        $row->{$field['colname']} = json_encode($request->{$field['colname']});
                        break;
                    case 'Files':
                        $files = json_decode($request->{$field['colname']});
                        $files2 = array();
                        foreach ($files as $file) {
                            $files2[] = "".$file;
                        }
                        $row->{$field['colname']} = json_encode($files2);
                        break;
                    default:
                        $row->{$field['colname']} = $request->{$field['colname']};
                        break;
                }
            }
            else if ($ftypes[$field['field_type']] == 'Checkbox'){
                // Checkbox has been cleared from the request so we have to remove the value 
                $row->{$field['colname']} = 0;
            }
        }
        return $row;
    }

**Comment by gdbhosale** [comment]
Hi @mgazelle ,

I appreciate your concerns...

This bug has been fixed in latest commit.
Soon new stable version will be created.

Thanks & Regards,
