### ISSUE TITLE
Modules with more than one word

### ISSUE THREAD

**Issue by mgazelle** [dwijitsolutions/laraadmin#27]
If you would create a module like Lead_statuses or Lead_ratings then the interface will not remove the underscore for the Add button, Titles and Tags unfortunately

**Comment by slozano95** [comment]
@mgazelle Hi, I just solved it next pull request will include it 2 days max

**Comment by mgazelle** [comment]
Thnx

Von meinem iPhone gesendet

**Comment by gdbhosale** [comment]
Fixed
