### ISSUE TITLE
Displaying Foreign Table value

### ISSUE THREAD

**Issue by mgazelle** [dwijitsolutions/laraadmin#28]
If you use the @ directive in the column definition to reference a foreign table for values, you can not show the value of the selected item in the index view. Instead the stored ID of the foreign table will be shown

Any plans to change this?

Thank you

**Comment by slozano95** [comment]
Hi, I have already made a pull request solving this foreign value

**Comment by mgazelle** [comment]
Thank you. I ll take a look

**Comment by mgazelle** [comment]
Models/Module.php around line 53 please add the $icon as below in your pull request

    public static function generate($module_name, $module_name_db, $view_col, $icon, $fields) {
        $names = LAHelper::generateModuleNames($module_name, $icon);

I am testing your changes

**Comment by mgazelle** [comment]
Another Issue when calling la:crud because the method generateConfig does not pass an icon

**Comment by gdbhosale** [comment]
You need to change your migrations for fa_icon.
You can call la:install again to get new migrations.

Closing this issue.

Best Regards,
