### ISSUE TITLE
Doesn't work on 5.6

### ISSUE THREAD

**Issue by pierrocknroll** [dwijitsolutions/laraadmin#284]
Hello,
When la:install, you change (and remove everything...) in Controller.php but trait AuthorizesResources doesn't exist so I have this error :

Trait 'Illuminate\Foundation\Auth\Access\AuthorizesResources' not found
in Controller.php (line 13)

The AuthorizesResources trait has been merged with the AuthorizesRequests trait.

But If I remove it, I have a page with this message on /admin:
"Record with not found"

Nothing in logs.

Thanks a lot

**Comment by emperorflame** [comment]
Hi @pierrocknroll .
Lara Admin currently available to Laravel 5.2 and 5.3
http://laraadmin.com/docs/1.0

**Comment by pierrocknroll** [comment]
So this project could be considered to dead
