### ISSUE TITLE
Feature request: Tables with relationships

### ISSUE THREAD

**Issue by mgazelle** [dwijitsolutions/laraadmin#29]
Something like an account with a shipping and a billing address (hasMany)

**Comment by gdbhosale** [comment]
Hi @mgazelle,

I appreciate your thought, but we have to integrate it manually after code generation.
Different developers will have different thoughts over this as we have facility to edit our module field after creation.
Let me know if you have a good plan for implementation strategy. I would appreciate that.

Best Regards,

**Comment by mgazelle** [comment]
I have changed this on my site to auto create the migration blocks you would create by hand in a migration file. All you have to do, is translate the field definition in the proper syntax of a migration file (Schema::create) and then append the foreign keys at the end.

I do not store the field definition in a table as mentioned in another issue post. I just translate the fields in proper laravel code which will adhere to Laravel docs and definitions.

I do not think personally a generator should write definitions back into the app database.

Another approach would be to reverse the DB schema. This way you create the DB and you are done with the rest.

**Comment by gdbhosale** [comment]
@mgazelle @slozano95 

Check inbuilt migrations.
Can we use relationship manual way like that ?

`File: 2014_12_01_000000_create_uploads_table.php`

```
if (Schema::hasTable('users')) {
	Schema::table('uploads', function ($table) {
		$table->foreign('user_id')->references('id')->on('users');
	});
}
```

It is also possible to reverse migrate this by putting similar syntax at end of up() method.

Let me know.

**Comment by mgazelle** [comment]
@gdbhosale 
This is in fact the Laravel way doing it. Relationship is in my opinion the most critical feature in the whole package. This would improve the package a lot. My suggestion would be:

1. check if the relationship is implemented in the DB (from the migration file or the module definition)
2. if not check the migration file to make sure it has not been appended
3. generate a new laravel migration file including just the foreign keys in the up method

If the relation is defined during the generation of the module then just append it to the up method

**Comment by gdbhosale** [comment]
@mgazelle @slozano95 I have completed with auto foreign key setting through Migrations as well as GUI. We can as well shift foreign keys from one table to another without fuss.
I am not very sure about way i have implemented it. Please go through the code.
Let me know your view. Hey @mgazelle You were quite right about this 👍 
Please report problems soon if they exists.

```
============ Module::create_field_schema (line 296) ============
$foreign_table_name = str_replace("@", "", $field->popup_vals);
if($update) {
	$var = $table->integer($field->colname)->unsigned()->change();
	if($field->defaultvalue == "" || $field->defaultvalue == "0") {
		$var->default(1);
	} else {
		$var->default($field->defaultvalue);
	}
	$table->dropForeign($field->module_obj->name_db."_".$field->colname."_foreign");
	$table->foreign($field->colname)->references('id')->on($foreign_table_name);
} else {
	$var = $table->integer($field->colname)->unsigned();
	if($field->defaultvalue == "" || $field->defaultvalue == "0") {
		$var->default(1);
	} else {
		$var->default($field->defaultvalue);
	}
	$table->foreign($field->colname)->references('id')->on($foreign_table_name);
}
```

Thank you guys...

**Comment by netinteractive** [comment]
Where you implement this? Do you plan to make add relations n:m (has many) throught GUI?

**Comment by gdbhosale** [comment]
Hi @mgazelle,

Foreign key linking with respective table is automatically handled by Custom Migrations.

You only need to write methods in Models.

Best Regards,
