### ISSUE TITLE
Feature Request: Unique validation

### ISSUE THREAD

**Issue by mgazelle** [dwijitsolutions/laraadmin#30]
Would be nice to have the unique validation implemented to avoid duplicate entries

**Comment by mgazelle** [comment]
Solved with a stub for create and update requests generated by need during the scaffolding process

**Comment by slozano95** [comment]
@mgazelle could you please create a pull request to include it?

**Comment by gdbhosale** [comment]
Yes @mgazelle, Its a necessary validation.

Let us know if you have any good plan to integrate it via JS & PHP without affecting the generated code.

Best Regards,

**Comment by mgazelle** [comment]
I might have another approach here which I think it adheres a bit more to laravel artifacts. I am working on a builder that would generate the migration, requests, and models for the application. Think about updating records which will definitely have to exclude the current id of the record, whenever a field is unique. I think the field definition should not be put back in the database itself, because the generator is a tool and not part of the application. It should facilitate the generation of the app and should be as a dev dependency in composer. the defition of a model done by a developer using laraadmin should be put back by the generator in request, model and migration files.

If you hwever would like to still put it down in the migration file, then this would be in an extra function exclusive to the generator to create then the real migration content. This way you can just run a migrate command on production and you are done.

The auto generated rules in a modified version of laraadmin auto generates the following code in the appropriate update request (Accounts module):

    public function rules()
    {
        return [
            'name' => 'required|min:3|max:64|unique:accounts,name,'.$this->route()->getParameter('accounts'),
            'phone' => 'required|phone:AUTO|unique:accounts,phone,'.$this->route()->getParameter('accounts'),
            'email' => 'required|email|unique:accounts,email,'.$this->route()->getParameter('accounts'),
            'website' => 'required|url',
            'rating' => 'required|exists:lead_ratings,id',
            'industry' => 'required|exists:lead_industries,id',
            'sales_agent' => 'required|exists:users,id',
        ];
    }
}

**Comment by gdbhosale** [comment]
Hi @mgazelle ,

I appreciate your views. I will work over it.

As of now i have merged the unique column support in migrations as well as UI.
Please check version 1.0.32

Best Regards,

**Comment by gdbhosale** [comment]
Hi @mgazelle,

Unique validation work is completed.

We haven't released the changes yet. Please checkout and let us know if any problem.

```
Module::validateRules() -->
if($field['unique'] && !$isEdit) {
	$col .= "unique:".$module->name_db.",deleted_at,NULL";
}
```

Closing this issue as of now.
Best Regards,

**Comment by mgazelle** [comment]
Hi Ganesh,

just busy with a deadline. I will definitely test again this weekend and will log all findings.

Thank you

**Comment by thecortex** [comment]
How about multiple unique columns?
