### ISSUE TITLE
dropdown but using integer as value

### ISSUE THREAD

**Issue by mohd-aidi** [dwijitsolutions/laraadmin#301]
Hi, how can i use dropdown but i want to use integer as the value?

[0=>'Papar Pilihan Individu dan Kumpulan', 1=>'Individu Sahaja', 2=>'Kumpulan Sahaja']

customize it in form maybe easy but in listing i cant find a way to change it.

**Comment by gdbhosale** [comment]
In this case you need to create these options as a Module and link it using `@options`

**Comment by mohd-aidi** [comment]
> In this case you need to create these options as a Module and link it using `@options`

you closed this when i dont even know what you talking. care to show me the guideline?
