### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [dwijitsolutions/laraadmin#304]
Hi, what is the current status of this project? Is it still actively maintained?

**Comment by leopinzon** [comment]
A nice project, unfortunately the owner doesn't give a f..ck. I have written to him in the past, here, to his twitter... etc., basically disappeared. Any new version in years, or bug fixes, pull requests unattended, etc etc

**Comment by DanielRuf** [comment]
> the owner doesn't give a f..ck.

Well, we do not know this or if something happened. Also not everyone is as active as many of us. There are often many factors (private life, other things, no more motivation, no time, ...).

**Comment by DanielRuf** [comment]
To be fair your activity graph and his are very similar ;-)

**Comment by DanielRuf** [comment]
And there are at least 6 persons with a public membership in this org which often have more rights than a normal contributor or collaborator.

https://github.com/orgs/dwijitsolutions/people

**Comment by leopinzon** [comment]
You asked and got and answer. You don't like it? your problem.

**Comment by leopinzon** [comment]
And FYI, those 6 members you mentioned are part of the company that built this project.

**Comment by DanielRuf** [comment]
No reason to be harsh. I just think he does not give no fuck but just has not really time for opensource, had a burnout or life is just more important. And I just wanted to clarify that there are more people than just him so why not wait for an answer? He is still active on Twitter.

**Comment by gdbhosale** [comment]
Dear Friends,

Thank for reaching out and mentioning your feelings. I respect that. Last 2 years were too rough (Financially + Mentally) for me to look at the progress of LaraAdmin. I haven't abandoned the Project yet. Unfortunately, I couldn't get any strong contributor outside my company to look over the issues. Pull request received on Project are not contributing majorly.

I am planning to create something worth for this Family to make their life easy in near future.

Please be open to sharing your suggestions and correction requests.

Best Regards,

**Comment by leopinzon** [comment]
My sincere apologies; I let my frustration speak for me on my first reply. Sorry to hear that @gdbhosale, I actually started loving this project and tried to contribute to it, but after so many months of silence I simply got tired.
Hope everything gets better to you :)

**Comment by perezcato** [comment]
I would like to contribute to the project.
Please let me know to you are ready for work to begin
