### ISSUE TITLE
Double error messages in the edit.blade.php

### ISSUE THREAD

**Issue by mgazelle** [dwijitsolutions/laraadmin#31]
Please remove the block:

				@if($errors->any())
				<ul class="alert alert-danger">
					@foreach($errors->all() as $error)
						<li>{{ $error }}</li>
					@endforeach
				</ul>
				@endif

**Comment by mgazelle** [comment]
Has to be removed from the view stubs

**Comment by slozano95** [comment]
@mgazelle ok thanks I have just included it in my pull request with your credit
Thanks

**Comment by gdbhosale** [comment]
Pull request by @slozano95 has been accepted and issues is resolved.

Thanks @slozano95
