### ISSUE TITLE
Errors on clean laravel 5.2 install

### ISSUE THREAD

**Issue by slozano95** [dwijitsolutions/laraadmin#32]
Hi
Today I was installing the package again and had to do some workaround

So to create a fresh 5.2 install 
`composer create-project laravel/laravel app 5.2`

But it shows some errors, to fix them change the scripts sections in `composer.json` to
`"scripts": {
        "post-root-package-install": [
        "php -r \"copy('.env.example', '.env');\""
    ],
    "post-create-project-cmd": [
        "php artisan key:generate"
    ],
    "post-install-cmd": [
        "Illuminate\\Foundation\\ComposerScripts::postInstall",
        "php artisan optimize"
    ],
    "post-update-cmd": [
        "Illuminate\\Foundation\\ComposerScripts::postUpdate",
        "php artisan optimize"
    ]
},`

Then add laraadmin package following instructions...

After installation, I tried to acces admin panel but there was the 

> undefined variable errors

To fix this move the Route:auth(); insdide the web middleware

`Route::group(['middleware' => ['web']], function () {
	Route::auth();
        

> and all routes

});`

Then generate a new key using `php artisan key:generate`

Hope it helps someone or we can fix it in the code

**Comment by gdbhosale** [comment]
This issue has been fixed in latest update.

Closing it. Best Regards,
