### ISSUE TITLE
Creation of fields of type Textarea (Richtext fields)

### ISSUE THREAD

**Issue by mgazelle** [dwijitsolutions/laraadmin#38]
When creating a field of type textarea (should correspond to text in the database), there should not be a min or a max required in the definition. Once submitted without values, an error is generated
QueryException in Connection.php line 761:
SQLSTATE[HY000]: General error: 1364 Field 'maxlength' doesn't have a default value (SQL: insert into `module_fields` (`colname`, `label`, `module`, `field_type`, `unique`, `defaultvalue`, `minlength`, `required`, `popup_vals`, `updated_at`, `created_at`) values (description, Description, 9, 21, 0, , 0, 1, , 2016-10-02 18:55:24, 2016-10-02 18:55:24))

Please exclude this check

**Comment by gdbhosale** [comment]
Fixed
