### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by SuperlativeEntity** [dwijitsolutions/laraadmin#4]
- Use custom requests in Controller
- Use ajax (post, get etc.)
- Use pjax
- Have a repository for each module. (repo pattern)
- Re-use your create and edit views. (It becomes a maintenance nightmare to manage)
- Multi-language support
- Use pivot tables for one-to-many relationships
- Drop down values need their own tables. E.g. media_type should not be ["Audiobook"], there should be a media_types table and the field should be media_type_id referencing the value via a foreign key.
- Multiple theme support

**Comment by gdbhosale** [comment]
Hello SuperlativeEntity,

These are really nice suggestions.
We have noted them.

As of now our focus is on providing basic functionality and get ready for thorough testing.

Thank you very much for your time spent reviewing the package.
We really do appreciate it.

Best Regards,
