### ISSUE TITLE
Error generating checkbox fiedls

### ISSUE THREAD

**Issue by mgazelle** [dwijitsolutions/laraadmin#40]
Same story, Max values should not be required here
QueryException in Connection.php line 761:
SQLSTATE[HY000]: General error: 1364 Field 'maxlength' doesn't have a default value (SQL: insert into `module_fields` (`colname`, `label`, `module`, `field_type`, `unique`, `defaultvalue`, `minlength`, `required`, `popup_vals`, `updated_at`, `created_at`) values (is_enabled, Enabled, 9, 2, 0, 1, 0, 1, , 2016-10-02 19:02:52, 2016-10-02 19:02:52))

**Comment by gdbhosale** [comment]
Fixed
