### ISSUE TITLE
Dropdown field should not require Maxlength

### ISSUE THREAD

**Issue by mgazelle** [dwijitsolutions/laraadmin#42]
QueryException in Connection.php line 761:
SQLSTATE[HY000]: General error: 1364 Field 'maxlength' doesn't have a default value (SQL: insert into `module_fields` (`colname`, `label`, `module`, `field_type`, `unique`, `defaultvalue`, `minlength`, `required`, `popup_vals`, `updated_at`, `created_at`) values (visibility, Visibility, 13, 7, 0, private, 0, 1, ["public","unlisted","private"], 2016-10-02 19:27:10, 2016-10-02 19:27:10))

**Comment by gdbhosale** [comment]
Fixed
