### ISSUE TITLE
Dropdown from table

### ISSUE THREAD

**Issue by mgazelle** [dwijitsolutions/laraadmin#43]
Busy with the definition of the modules but not yet migrated, you should be able to select a table based on a module once you select the type Dropdown. The list of tables shows only already migrated tables. This way you have to migrate every module first before going further with the rest, if you plan to have relationships

**Comment by gdbhosale** [comment]
We have kept the that because of foreign keys for relationship which we are planning to implement.

**Comment by mgazelle** [comment]
Is it now solved or you have just closed the issue?

**Comment by gdbhosale** [comment]
We cannot create foreign keys when database tables aren't migrated...

**Comment by mgazelle** [comment]
I think we have a miscommunication.

We can surely define the whole modules and then migrate once. The definition of the relationship does not require the existence of the table in the DB, it requires however the definition within the module even if it is not generated

I have a different view regarding this issue which is still priority one in my opinion
