### ISSUE TITLE
Fresh Install - Save/Update issue

### ISSUE THREAD

**Issue by grizzdev** [dwijitsolutions/laraadmin#5]
Ran through install documentation.
Logged into admin.
Opened employee for editing.
Didn't change any of the fields, clicked "Update" button.
Received the following error:
ErrorException in Module.php line 516:
Array to string conversion

Tried the same process with Roles and Departments, same result.  What did I miss?

**Comment by gdbhosale** [comment]
Hi Mathieutu, Thank you very much for considering LaraAdmin. I am currently working on the same. Till Monday this will be finished. You cannot create users directly. You can create Employee and user will be created in background. This is not implemented yet. Please stay tuned... Will reply you once it is done. If you have anything in mind for Access Control, let me know. Good day.

**Comment by gdbhosale** [comment]
Hi @grizzdev

Please try again the process. We have addressed all installation related issues in version 1.0.10.

Please update the package and try again.

Thanks for using LaraAdmin.

Best Regards,
