### ISSUE TITLE
Default access for Super admin

### ISSUE THREAD

**Issue by mgazelle** [dwijitsolutions/laraadmin#52]
Once a new module has been created it should be by default accessible for the Super Admin role

**Comment by slozano95** [comment]
@mgazelle I think you are looking some old commit, please update from source,this has already been made

**Comment by mgazelle** [comment]
I just installed it today. The Role Super Admin is activated but the create, delete, edit and list are not

**Comment by slozano95** [comment]
@mgazelle are you installing from composer?

**Comment by mgazelle** [comment]
Yes

**Comment by slozano95** [comment]
@mgazelle  that's the reason you may want to replace vendor/dwij/laraadmin folder with the one from git clone https://github.com/dwijitsolutions/laraadmin/

Then execute php artisan la:install

**Comment by mgazelle** [comment]
That is fine. I am always testing with the composer version.

I hope I will find some time to clone the repo and be more active in the project.

Thank you

**Comment by gdbhosale** [comment]
Hello @mgazelle ,

We haven't released the stable version as we have so many features under development.

You can use git clone for work as of now.

Closing this issue.

Best Regards,

**Comment by mgazelle** [comment]
Hi,

That is ok, but once released and the issue is still there then you will get it lost.

**Comment by slozano95** [comment]
@mgazelle don't worry this issue has already been solved and will be included in next release
