### ISSUE TITLE
Field Type Image wont show in the list

### ISSUE THREAD

**Issue by mgazelle** [dwijitsolutions/laraadmin#53]
If the following field type is created, it will not be shown in the view list (Index view) and instead it is shown as an integer 1

["profile_image", "Profile Image", "Image", false, "img_path.jpg", 0, 250,  false],

**Comment by gdbhosale** [comment]
Please check OrganizationsController for implementation.

**Comment by sanathpathiraja** [comment]
I follow the OrganizationsController for implementation.
then added this into employee
show.blade -> @la_display($module, 'profile_image')
and
index.blade
@la_input($module, 'profile_image')

but it gives nothing.
help me.

**Comment by gdbhosale** [comment]
Please Check Module and Module Field Permission for your Role.

**Comment by sanathpathiraja** [comment]
Yes thanks.
It's working.
