### ISSUE TITLE
Field Type checkbox: View representation

### ISSUE THREAD

**Issue by mgazelle** [dwijitsolutions/laraadmin#54]
Field Type Checkbox would be better to get represented with font awesome in the views

Definition:
["is_enabled", "Enabled", "Checkbox", false, "1", 0, 0, true],

View Representation:
if($fields_popup[$col] != null && $fields_popup[$col]->field_type == 2) {
                    $data->data[$i][$j] = $data->data[$i][$j] == 1 ? '<i class="fa fa-check-square-o"></i>' : '<i class="fa fa-square-o"></i>';
}

**Comment by gdbhosale** [comment]
Hey @mgazelle 

Can you make a pull request for the same ?

Best Regards,
