### ISSUE TITLE
Models Directory as a config value

### ISSUE THREAD

**Issue by mgazelle** [dwijitsolutions/laraadmin#56]
Would be nice to have a conf variable in laraadmin.php to define the location of Models

Is much better to have them in a folder

**Comment by gdbhosale** [comment]
@mgazelle Nice suggestion. Will look into it.

@slozano95 Can you work this out ?
We need to change model paths in la:install + packaging + crud-generation.

Let me know.

Best Regards,

**Comment by slozano95** [comment]
@mgazelle this is done now please @gdbhosale close this issue

**Comment by mgazelle** [comment]
Should not we test it first?

You are closing issues very fast and I m not a real fun of this because it will be reflected in the quality back

**Comment by slozano95** [comment]
@mgazelle I have been working on this like all week, ganesh and me have already test this out, as I was working cause I was making a custom folder path, but it had so so so many issue so now folder is located ar App/Models, if we let users define this path it will carry so many problems like controllers and external packages issue as zizaco/entrust (it requires User,Role and Permission model to be at /app folder)

**Comment by mgazelle** [comment]
@slozano95 this is not a correct statement. Even the User Model which is very essential to laravel is configurable and I have been able to create folders inside the app directory for Models. I am not saying that putting the Models in a predefined folder like Models is not a good idea, but I guess if this is an open source project than decisions have to be at least between involved parties, otherwise it will be really a waste of time if someone invests time getting things better and under the hood tickets are silently closed.

it is surely your decision as it is your project but success in open source lives from discussions and opinions.

**Comment by slozano95** [comment]
@mgazelle i know , and let me tell you Im not being rude, Im sorry if you misunderstand my opinion as I am not native English speaker some of my comments might sound bad sorry for that, 
I f you want you might solve this, on my repo you should find all my commits on custom folder I was using s config value to create and manage the models but when working on entrust it required me to use base models so as It is an external package we decide this models should be outside, if you found a good solutions on this tell us please
Best regards

**Comment by mgazelle** [comment]
in 5.3 Laravel has introduced Gates, Abilities and other concepts which are just perfect out of the box. I do not know to be honest if it is a good decision to still use entrust as it has other issues too as you know which are not suitable for production. I m now fixing few bugs from laraadmin like skins ans layouts which should be in the config file and not in the controller and I wish I will have time to get to the relationships and models.

it was just my opinion by the way and because I have evaluated dozens of packages for CRUD and Admin, I thought I might pass you my comments because I find your package with some minor remarks one of the best.

Anyhow we will see how things will evolve in the future

**Comment by gdbhosale** [comment]
Dear @mgazelle,

We have to maintain this package support for Laravel 5.2 as well.
Can you provide solution that uses features of 5.3 and works with 5.2. We would be happy to see that. If not please don't spoil the fun out of coding.
Try to provide the solution not problems.

Best Regards,

**Comment by mgazelle** [comment]
Spoil? well no comment

**Comment by mgazelle** [comment]
BTW: This has nothing to do with 5.2 and 5.3. It is just a value you read during install and then you have it in your config. Whenever you create a model you namespace it correctly and you put it in the same directory! This is the solution as simple as this!

**Comment by mgazelle** [comment]
And in order to get a better quality, problems have to be addressed so do not take the comments personal

**Comment by slozano95** [comment]
@mgazelle the solution as simple as this you provide might look easy but believe me It is not just like that, lots of files should be updated and some of them are outside the LaraAdmin enviroment, so you might now that anything outside your IS is a black box so no control over others decision, if you find a viable solution, we will be glad to hear it from you, but for now I think the issue should be closed
Best Regards
