### ISSUE TITLE
Change the icon in the show view

### ISSUE THREAD

**Issue by mgazelle** [dwijitsolutions/laraadmin#57]
Would be nice to set the icon of the show view to the icon selected for the module instead of the fa-cube

Please change this line
<div class="profile-icon text-primary"><i class="fa fa-cube"></i></div>

with this one
<div class="profile-icon text-primary"><i class="fa {{ $module->fa_icon }}"></i></div>

**Comment by slozano95** [comment]
@gdbhosale duplicated

**Comment by gdbhosale** [comment]
@mgazelle duplicated
