### ISSUE TITLE
Issues in admin/modules

### ISSUE THREAD

**Issue by mathieutu** [dwijitsolutions/laraadmin#6]
Hi,
I'm trying to understand how modules works.
I'm on a fresh install. 

- If I go on any module in `/admin/modules/` I have a blank page on Edit route.
- All modules are marked as not generated.
- When I'm trying to create a module  : "view_column_name not found in field list."
- If I'm trying to generate a CRUD for user, I've a 500 error (no view)
- Also, there isn't anything generated for users at start ? 

Thank's for your answer, and for your amazing job !
:-)

**Comment by gdbhosale** [comment]
Hi, This is not implemented fully. You can create modules via two commands. la: migration and la:crud. Please check documentation for more. laraadmin.com/documentation

**Comment by gdbhosale** [comment]
Hi @mathieutu,

We have completed our Module Field Editor where you can change the fields type, name and other contexts.

Regards,
