### ISSUE TITLE
Setting Cache Array

### ISSUE THREAD

**Issue by mgazelle** [dwijitsolutions/laraadmin#60]
First time using la:install and setting cache to array does not work. setting is written to the .env file but the install files. The seond run of la:install gets through

**Comment by slozano95** [comment]
@mgazelle yes unfortunately we can not set env variables while running a
command next PR includes a line to rerun la:install
Thanks

**Comment by mgazelle** [comment]
Going to run few new tests and see where we are. Working with a clone now so I can make pull requests in the future if needed

**Comment by gdbhosale** [comment]
Thanks @mgazelle,

Have you done PHP unit testing for packages...
We want to implement that as well.

Regards,

**Comment by mgazelle** [comment]
Yes I did

right now I am solving two issues. One regarding the models directory and the other one regarding the site name. I am adding this to the installer, because these two are important for the consistency

If I ll find some time I ll fix the env issue as well.

after that I would like to handle the relationships because this is really essential.

I have finally forked the repository and I m working with the studio package to stay in sync.

If you are doing any of these tasks please let me know

**Comment by mgazelle** [comment]
Please use dev-laravel-5 for the Entrust package to get rid of the whole array cache because it is not recommended for production. I changed this in my forked version already

**Comment by slozano95** [comment]
@mgazelle im working on model folder check my forked repo

**Comment by mgazelle** [comment]
OK, Thank you.

I just moved the site name in the DB now and removed it from the config file because that was double

**Comment by mgazelle** [comment]
I fixed this one already in LAInstall and I will publish it shortly

**Comment by slozano95** [comment]
@mgazelle thanks, please close the other issue about app name

**Comment by gdbhosale** [comment]
This Issue has been resolved. Please Update & confirm.
