### ISSUE TITLE
Setting the Application name

### ISSUE THREAD

**Issue by mgazelle** [dwijitsolutions/laraadmin#61]
Setting the Application name to a custom name works fine in the Frontend. Backend remains using the name Lara Admin 1.0

**Comment by mgazelle** [comment]
I see the configuration of the name is now in the configuration menu. Isn't it better to have it in one place? Config or DB?

**Comment by slozano95** [comment]
@mgazelle it should be included in config GUI inside admin panel, can you help me fixing this?

**Comment by mgazelle** [comment]
I think you mean version. Name is already there. Please check my fork and you will find the change. The GUI will be adjusted shortly

**Comment by slozano95** [comment]
@mgazelle yes I saw that , you might want to create a pull request so we can merge to master repo

**Comment by gdbhosale** [comment]
Done. Now you can set it in Configuration.
One more thing. `db:seed` command is compulsory to run, in order to load basic configuration into database hence the sitename.
Regards,
