### ISSUE TITLE
Creating Backup is failing

### ISSUE THREAD

**Issue by mgazelle** [dwijitsolutions/laraadmin#64]
After a clean install, creation of a backup is failing with the message "failed to create a backup". Pretty sure it has to do with rights to access the mysqldump command. If so this should be documented.

**Comment by mgazelle** [comment]
Just debugged this issue and it has to do with the path to the dump binary. Should be included in the config section instead of hardcoded because of the derivation of underlying OS

/opt/lampp/bin/mysqldump

in my case just

/usr/bin/mysqldump

**Comment by gdbhosale** [comment]
Hi @mgazelle ,

I had a thought over this and shown proper error message for user to correct config/database.php
->dump_command_path

We cannot move this setting as this is processed by another package.
We have only option to show error and give proper suggestion.

Best Regards,

**Comment by mgazelle** [comment]
I have added to the installer a configuration option to enter the path and write it back to the database config file.

even using the right path backup is still failing and I have to debug it.

Please do not close issues fast until we have a solution for them otherwise I will be wasting my time in this package.

The backup feature is still not as it should be
