### ISSUE TITLE
Appending routes

### ISSUE THREAD

**Issue by mgazelle** [dwijitsolutions/laraadmin#67]
This is an issue if you run la:install again and again. A fresh laravel install has no valuable routes in the web.php and therefore it would be better to copy the web file and not to append to it

**Comment by gdbhosale** [comment]
We are not replacing it because, user can have his earlier routes inside it.
We don't want to flush his data.
Regards,

**Comment by mgazelle** [comment]
LaraAdmin as mentioned in your webpage should be used on a clean Laravel install.

If this is not the case then this is buggy because each run of install append s the same routes again and again

**Comment by gdbhosale** [comment]
I never mentioned that you can use only on fresh install. I might not have created package then.
As simple as that...

We can't call it buggy until we release full documentation about install command.
There would be a upgrade command to update new version of laraadmin.
We cannot create everything automatic. Its not possible.
There are some works which are better done manually.

**Comment by gdbhosale** [comment]
Done. Update latest commits
