### ISSUE TITLE
Please use Container Div

### ISSUE THREAD

**Issue by mgazelle** [dwijitsolutions/laraadmin#69]
The layout of views is not conform to the Bootstrap specs. Rows have to be placed within a Container div

**Comment by mgazelle** [comment]
I have just fixed this in the app.blade.php and will commit it in a bit. Please close the issue once you pull the change

thnx

**Comment by gdbhosale** [comment]
@mgazelle, I don't see any changes in app.blade.php

**Comment by gdbhosale** [comment]
@mgazelle, Please elaborate the the problem in details.
