### ISSUE TITLE
How do the users work?

### ISSUE THREAD

**Issue by mathieutu** [dwijitsolutions/laraadmin#7]
Hi, I'm new on your amazing project, and I'm trying to understand how Users management works.

I've seen : 
- User model with a UserType, and with the first user
- A Employee Model, but without link with UserType or globally with User, and with the same first user
- A Role Model but without any link with the both previous models, with the role of the first user

How have you planned to manage access with all of that?

Thank you for your answer, and again, for your amazing job!

**Comment by mathieutu** [comment]
Ok, I've juste seen that is not implemented yet..
Really too bad, I was planning to use your package for a new project.
Do you know when the feature will come ?

Thx

**Comment by gdbhosale** [comment]
Hi Mathieutu, Thank you very much for considering LaraAdmin. I am currently working on the same. Till Monday this will be finished. You cannot create users directly. You can create Employee and user will be created in background. This is not implemented yet. Please stay tuned... Will reply you once it is done. If you have anything in mind for Access Control, let me know. Good day.

**Comment by gdbhosale** [comment]
Hi Mathieutu,

We have addressed half the issue regarding users & roles in version 1.0.10.
Please update the package and install again.

We are working on User Access Control part.
It will take little time.

Please stay tuned. Follow our twitter account (twitter.com/laraadmn) to get latest updates.

Let us know if anything on your mind over Access Control.

Best Regards,

**Comment by gdbhosale** [comment]
Hello @mathieutu ,

Hope you are doing good.

We have completed the Module Authentication based on SugarCRM Philosophy.
We have also provided addition authentication via Zizaco/Entrust.

Please check latest update.

It may not work fully over Laravel 5.3. Work is under progress.

Closing this issue... Please don't hesitate to reply :+1: 

Best Regards,

**Comment by azenmoktan** [comment]
sir i used laraadmin n its quite good but now i am working on a quick project for role based system so i thought of using it again but seems like laraadmin doesnt have that functionality for creating role based user or is there a way to achieve that ?

**Comment by gdbhosale** [comment]
Hi, We have created Role based users and also used two types of access control in it.

1. Roles based permissions using Zizaco/Entrust
2. Modular permissions for add, edit, delete + field level permissions.

Documentation related to this is not available yet.

Please check functionalities after installation.

Regards,

**Comment by azenmoktan** [comment]
isnt there any documentation on that ?cuz i was hopping to use laraadmin on
my next project .i needed login for admin teacher and student

**Comment by jnorvor** [comment]
Hello just wondering if the documentation  for using Zizaco/Entrust is available now?

**Comment by Ethosteck** [comment]
Hi Team,
Tremendous Effort, I am still wondring if roles and permision is implemented in laravel 5.3 as i have created roles, users, permission but still not able to use it. i was going through code but it jumps from my head. Please i am awaiting for help on the above issue if its implemented please guide me how i can achieve this. @gdbhosale
