### ISSUE TITLE
Please store checkbox values as a bit

### ISSUE THREAD

**Issue by mgazelle** [dwijitsolutions/laraadmin#70]
Usage of keywords to store bit values is not recommended. LAConfigs is storing values as on and off and in other tables we have enabled and disabled.

To be consistent it would be much better to store it as a bit 0 or 1 and in the interface you might you enums to translate the setting

**Comment by mgazelle** [comment]
Just changed these in the views and the seeder, if interested, please check my fork end of the day to pull it

thnx

**Comment by gdbhosale** [comment]
@mgazelle, LAConfigs is not just limited to Checkboxes.
Having value in on and off won't affect anything.
Regards,

**Comment by mgazelle** [comment]
That is not the point. I know it is not limited to Checkboxes but saving the checkbox value as on and off was my comment.

**Comment by gdbhosale** [comment]
Does it matter ?
