### ISSUE TITLE
MS SQL Server - error converting date / time

### ISSUE THREAD

**Issue by juanlock** [dwijitsolutions/laraadmin#77]
Thanks you for your template
i just installe and configure for SQL, 
installation done.. but when i try to add any record (deparment, company) i receive this error 

This error when i try to add one record on department.

QueryException in Connection.php line 764:

SQLSTATE[22007]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Conversion failed when converting date and/or time from character string. (SQL: select count(*) as aggregate from [departments] where [deleted_at] = mis)

**Comment by gdbhosale** [comment]
Hello @juanlock,

We recommend to use either MySQL or SQLite server for LaraAdmin.
We officially don't work on Windows. Neither do i have Windows Machine.

Can you please fix this error by yourself.
Please let us know the correction in our package to accommodate SQL Server.

Best Regards,

**Comment by juanlock** [comment]
Thanks i will test in Mysql.
