### ISSUE TITLE
Using Themes

### ISSUE THREAD

**Issue by Rav23** [dwijitsolutions/laraadmin#78]
Hi there, I love Laraadmin <3

I recently bought a theme from Creative Market and I would like to use it with laraadmin but haven't figured out a way to do so. Any insight on this? The theme has almost all JS Plugins that ADMINLTE does.

**Comment by gdbhosale** [comment]
LaraAdmin is backend Panel. You can set theme for front application simply by using hom.blade.php and main.css.

Changing Admin Panel theme will be very difficult. You need to do it properly.

**Comment by gdbhosale** [comment]
Hi,

LaraAdmin is backend Panel. You can set theme for front application simply
by using hom.blade.php and main.css.

Changing Admin Panel theme will be very difficult. You need to do it
properly.

Let me know your concerns...

Best regards,

**Comment by gdbhosale** [comment]
Hi,

You can now extend this package to have your own theme + logic.

Check http://laraadmin.com/docs/1.0/extending

Closing the issue.
