### ISSUE TITLE
Exception LAInstall::handle Unable to install on clean project

### ISSUE THREAD

**Issue by rxstriker** [dwijitsolutions/laraadmin#80]
I'm trying to install LaraAdmin on a new laravel project in order to test and possibly customize it for my needs. But I can't install it due to a migration error, today is the create_jobs_table yesterday was a problem with the create_notification_category_notification_group_table. Here's some of the stack trace:
```
LAInstall::handle exception: ErrorException: Undefined index: 2016_09_15_170641_create_jobs_table in /opt/lampp/htdocs/aliartalentos-laravel53-laraadmin/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:252

[2016-10-25 09:57:28] local.ERROR: Exception: LAInstall::handle Unable to install : Undefined index: 2016_09_15_170641_create_jobs_table in /opt/lampp/htdocs/aliartalentos-laravel53-laraadmin/vendor/dwij/laraadmin/src/Commands/LAInstall.php:329
                                                          
[Exception]                                                                  
LAInstall::handle Unable to install : Undefined index: 2016_09_15_170641_create_jobs_table 
```
And a screenshot of yesterdays exception:
![screenshot from 2016-10-24 12-15-59](https://cloud.githubusercontent.com/assets/23050598/19682270/b8f1f826-9aa4-11e6-8845-4e2b31588658.png)

**Comment by gdbhosale** [comment]
Dear @rxstriker,

Please delete all tables from your database including migrations. This database is having old migrations listed in it like `create_jobs_table`.

This does not belongs to LaraAdmin.

After flush run:

```
php artisan migrate
php artisan db:seed
```

This will work for sure.

**Comment by rxstriker** [comment]
@gdbhosale sry for troubling you. The issue was related to a wrong db declaration in .env file.
My fault
