### ISSUE TITLE
Integrity constraint violation when updating SUPER_ADMIN role

### ISSUE THREAD

**Issue by rxstriker** [dwijitsolutions/laraadmin#82]
I was trying to configure various aspects of LaraAdmin using the Configuration menu in the dashboard, one of those aspects is translating the display names to my language. The role in question is SUPER_ADMIN
When updating I ran into:
`SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails ('aliartalentos_laraadmin_crm'.'roles', CONSTRAINT 'roles_parent_foreign' FOREIGN KEY ('parent') REFERENCES 'roles' ('id')) (SQL: update 'roles' set 'display_name' = Super Administrador, 'parent' = 0, 'updated_at' = 2016-10-27 16:45:15 where 'id' = 1)`

**Comment by gdbhosale** [comment]
Hi @rxstriker,

There is a little change in `LA\RolesController.php`

```
if($request->name == "SUPER_ADMIN") {
	$request->parent = 1;
}
```
This will solve the problem. Laravel does not allow nullable foreign keys.

Closing the issue 👍
