### ISSUE TITLE
Laraadmin backups  problem

### ISSUE THREAD

**Issue by edisonr17** [dwijitsolutions/laraadmin#83]
hi.

I have this problem 

 local.ERROR: http://localhost backups : error: Failed to backup  because: The dump process failed with exitcode 1 : General error : El sistema no puede encontrar la ruta especificada.

I'm trying to change the route in BackupsController 

![image](https://cloud.githubusercontent.com/assets/7017442/19810410/fd09f432-9cf2-11e6-958d-2de0b7ccd82a.png)

**Comment by gdbhosale** [comment]
@edisonr17 

I think there is some problem in `mysqldump` command on your system (If you are using MySQL).

Let us know what is your database system.

Regards,

**Comment by edisonr17** [comment]
The problem was in config/database.php 

The value in 'dump_command_path' had a path of linux and i am working in windows :S

![image](https://cloud.githubusercontent.com/assets/7017442/19860156/b84ab2e0-9f55-11e6-8026-84866132a2ea.png)
