### ISSUE TITLE
Class 'App\Http\Controllers\LA\LAConfigs' not found when updating employee/user password and creating employee does not request password

### ISSUE THREAD

**Issue by rxstriker** [dwijitsolutions/laraadmin#84]
When updating a employee/users password after creating:
`
FatalThrowableError in EmployeesController.php line 330: Class 'App\Http\Controllers\LA\LAConfigs' not found
`
And I've noticed that the Employee store method in the EmployeesController.php creates a new user using a password sent through a request. But when I tried to create an employee, it did not ask me for a password.

**Comment by gdbhosale** [comment]
@rxstriker,

Password is automatically generated for newly created User. If you configure the smtp in .env it will send mail with login details like WordPress does. If smtp is not set, it saves details in log file.

LAConfigs is ia there in LaraAdmin package.

Add this line in EmployeeController:

use Dwij/Laraadmin/Models/LAConfig;

It will work.
