### ISSUE TITLE
Integrate your media manager

### ISSUE THREAD

**Issue by minedun6** [dwijitsolutions/laraadmin#88]
Is it possible to integrate your media manager with one of my app ?
I'm just testing out some packages for my end term project and your package seemed like the right choice.

**Comment by gdbhosale** [comment]
Yes. It can be.

Laravel has json REST API's which can fetch data from `uploads` table.

You can customise it yourself by forking our packages check https://getcomposer.org/doc/05-repositories.md#vcs.

Best Regards,
