### ISSUE TITLE
Datatables  - File Export

### ISSUE THREAD

**Issue by juanlock** [dwijitsolutions/laraadmin#89]
Hello , that really awesome project, and thanks a lot.

I would like to implement some reports of tables for my customer.. and would like some guide for to get the option File Export and print on the Datatables ?
https://datatables.net/extensions/buttons/examples/initialisation/export.html

Could you help me ?

**Comment by juanlock** [comment]
any news with this.. i would like to complete my project and those (export to pdf, cvs and print) options will be very very much easy..

**Comment by gdbhosale** [comment]
Hello @juanlock,

I appreciate your concerns.

LaraAdmin generated CRUD's provides basic functionality only. So that developers will get freedom to enhance them at will. Over-customisations from our/package side will ruin the fun. You can do this yourself after CRUD files are is generated for a module.

Let me know your views.

Regards,

**Comment by juanlock** [comment]
I understand perfectly, and I believe your support to the community is great,
but in my case, I consider myself a novice in programming, it is possible to know the routes / files correctly to get the "js" of Datatables, Will be easier to get add more functionally ( I will check Datatables official website for to know how to add these features.)

thank you very much.

I promise that when I get it, I will share with the community.

**Comment by slozano95** [comment]
@juanlock check it out
First, add this lines to the required  view in index.blade.php  at the end of the file inside the push('styles')
`<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.min.css"/>`

Then inside push('scripts') add this 
```
<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script src="//cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
<script src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
<script src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
<script src="//cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
<script src="//cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
```

Then inside the Datatable function add your DOM which enables you to draw the buttons (B) after the lenght control (l), the DOM option lets you organize your layout, check Datatables docs for futher details

```
dom: 'lBfrtip',

buttons: [
        'copy', 'csv', 'excel', 'pdf', 'print'
],

```

You should end with something like this

```
@push('styles')
<link rel="stylesheet" type="text/css" href="{{ asset('la-assets/plugins/datatables/datatables.min.css') }}"/>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.min.css"/>
@endpush

@push('scripts')

<script src="{{ asset('la-assets/plugins/datatables/datatables.min.js') }}"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script src="//cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
<script src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
<script src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
<script src="//cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
<script src="//cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
<script>

$(function () {
	$("#example1").DataTable({
		dom: 'lBfrtip',
		buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ],
		processing: true,
        serverSide: true,
        ajax: "{{ url(config('laraadmin.adminRoute') . '/asistencia_dt_ajax') }}",
		language: {
			lengthMenu: "_MENU_",
			search: "_INPUT_",
			searchPlaceholder: "Search"
		},
		
		@if($show_actions)
		columnDefs: [ { orderable: false, targets: [-1] }],
		@endif
	});
	$("#asistencia-add-form").validate({
		
	});
});
</script>
@endpush`

I have already tested this code so no problems should rise, but keep us updated

Regards

**Comment by juanlock** [comment]
Thanks a lot,  Santiago,

I appreciate your help; this will reduce the time for finish my personal project. I will keep post about this.




Si me necesita para algo aqui estare,

tengo hosting, website y demas..



Regards,

Sincerely,


                              Juan Lock

                   System Engineer (15 Years)

               Specialist Information Technology


Certifications:

           CNE, MSCE,Linux Expert.

     Symantec Technical Specialist (STS)


            Website development and Portals

Installation and Network Servers (Microsoft, Novell and Linux)

   Implementation of Security Systems (Firewalls)

PS: Please do not print this email unless it is necessary, care for the planet.


________________________________
