### ISSUE TITLE
Array to string conversion error

### ISSUE THREAD

**Issue by richardkeep** [dwijitsolutions/laraadmin#9]
Thanks for the good work.

However whenever I try to create a new record or edit an existing record, I get this error message:

```
ErrorException in /home/vagrant/Code/eaas/vendor/dwij/laraadmin/src/Models/Module.php line 537:

Array to string conversion
```

I am on Laravel Homestead with:
- Laravel v5.2
- dwij/laraadmin v1.0.12

I can't figure out what's wrong.

**Comment by gdbhosale** [comment]
Hello richardkeep,

Can you send me your migration file for which you get this error ?

Thanks

**Comment by richardkeep** [comment]
I have not added any new module to the application. I just installed LaraAdmin and tried adding a new Organisation. It throws that error. I tried creating a new user also. It throws the same error, so I couldn't proceed from there.

**Comment by shinokada** [comment]
Same here.

**Comment by gdbhosale** [comment]
Hello richardkeep & shinokada,

Please give me details of error and data fed to it through your browser from request.
I am not able to replicate error you described.

Please provide log if possible.

Best Regards,

**Comment by shinokada** [comment]
[log](https://drive.google.com/file/d/0B11mVUatZkcjMlczdENjQVF5MFk/view?usp=sharing)

**Comment by piyushbagri** [comment]
I have the same issue
Quick fixed by replacing $request->$field['colname'] to $request->{$field['colname']} on line 537 of /vendor/dwij/laraadmin/src/Models/Module.php 
and 
apply same in method 
public static function processDBRow($module, $request, $row) {
        $ftypes = ModuleFieldTypes::getFTypes2();
        
        foreach ($module->fields as $field) {
            if(isset($request->{$field['colname']})) {
                
                switch ($ftypes[$field['field_type']]) {
                    case 'Checkbox':
                        #TODO: Bug fix
                        $row->{$field['colname']} = $request->{$field['colname']};
                        break;
                    case 'Date':
                        if($request->{$field['colname']} != "") {
                            $date = $request->{$field['colname']};
                            $d2 = date_parse_from_format("d/m/Y",$date);
                            $request->{$field['colname']} = date("Y-m-d", strtotime($d2['year']."-".$d2['month']."-".$d2['day']));
                        }
                        $row->{$field['colname']} = $request->{$field['colname']};
                        break;
                    case 'Datetime':
                        #TODO: Bug fix
                        if($request->{$field['colname']} != "") {
                            $date = $request->{$field['colname']};
                            $d2 = date_parse_from_format("d/m/Y h:i A",$date);
                            $request->{$field['colname']} = date("Y-m-d H:i:s", strtotime($d2['year']."-".$d2['month']."-".$d2['day']." ".substr($date, 11)));
                        }
                        $row->{$field['colname']} = $request->{$field['colname']};
                        break;
                    case 'Multiselect':
                        #TODO: Bug fix
                        $row->{$field['colname']} = json_encode($request->{$field['colname']});
                        break;
                    case 'Password':
                        $row->{$field['colname']} = bcrypt($request->{$field['colname']});
                        break;
                    case 'Taginput':
                        #TODO: Bug fix
                        $row->{$field['colname']} = json_encode($request->{$field['colname']});
                        break;
                    default:
                        $row->{$field['colname'] }= 
                        $request->{$field['colname']};
                        break;
                }
            }
        }
        return $row;
    }

**Comment by richardkeep** [comment]
@piyushbagri Your solution works. Thank you! :+1:

**Comment by shinokada** [comment]
Yup, it works. But why do you need to add a curly bracket? Any idea?

**Comment by gdbhosale** [comment]
@piyushbagri Thanks for the solution !!!
I have updated same on version 1.0.14.

Please let me know on which Operating System and PHP version you were receiving this error.
I am using Mac OS. I haven't seen this error ever. Will take care if get more details of bug.

Thanks & Regards,
@gdbhosale

**Comment by shinokada** [comment]
PHP 7.0.8
OSX 10.11.5

**Comment by richardkeep** [comment]
PHP Version 7.0.2
Laravel Homestead 0.4.1

**Comment by gdbhosale** [comment]
Thank you guys for your contribution.

I think problem was because of PHP 7. I am currently using PHP version 5.5.
Will test on 7 too. Let me know if any more bugs. Closing this issue.

Best Regards,
