### ISSUE TITLE
Error while deleting a module

### ISSUE THREAD

**Issue by Sarav-S** [dwijitsolutions/laraadmin#90]
When I tried deleting an already existing module, I get following error.

<img width="1115" alt="screen shot 2016-10-31 at 11 52 57 am" src="https://cloud.githubusercontent.com/assets/3178230/19845833/9b822502-9f60-11e6-8b84-0dd9e8157001.png">

**Comment by slozano95** [comment]
Hi @Sarav-S please check if you have installed the Code Editor the right way (composer update)

**Comment by slozano95** [comment]
@Sarav-S also make sure you run php artisan la:editor to enable laeditor
I have been trying to replicate your error with no success
Could you please give use some further details?

Regards
