### ISSUE TITLE
Generated edit.blade.php has incorrect cancel button

### ISSUE THREAD

**Issue by kolexndr** [dwijitsolutions/laraadmin#92]
I've found cancel button doesn't work in FF and IE as desired.  It submits form instead of just returning back.
i've inpspected HTML code and found anchor tag inside button tag.  This is an issue for specified browsers, Please fix.  (removing tag button and set class attribute of anchor to "btn btn-default pull-right" work just fine)
Thanks!

**Comment by gdbhosale** [comment]
Thank you @kolexndr 

Fixed in `dev-master`

Closing issue...
