### ISSUE TITLE
WYSIHTML5 on html fields

### ISSUE THREAD

**Issue by rudiboot** [dwijitsolutions/laraadmin#93]
How do you enable WYSIHTML5 on html fields?

thanks

**Comment by rudiboot** [comment]
$(".htmlbox").wysihtml5();

**Comment by gdbhosale** [comment]
Hello @rudiboot 

Thanks for the concerns.
You can do this yourself by changing the `public/la-assets/js/app.min.js:175`:

```
/* ================= HTML ================= */
$(".htmlbox").wysihtml5();
$(".htmlbox").on("blur", function() {
	console.log("htmlbox.blur");
	$(this).next().val($(this).html());
});
```

We are planning to implement http://summernote.org in future.

Best Regards,

**Comment by rudiboot** [comment]
Thanks Ganesh, also need to add the following in the edit.php template

@push('styles')

<link rel="stylesheet" href="{{ asset('la-assets/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">
@endpush

@push('scripts')
<script src="{{ asset('la-assets/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script>
<script>
