### ISSUE TITLE
multiple files upload in module(images)

### ISSUE THREAD

**Issue by JerryKrakel** [dwijitsolutions/laraadmin#95]
Hi,

I'm quite new with laravel but somewhere you have to learn it. 

I made a module imagegalleries, with multiple files/images in it. 
Now im trying to get them into my view to show up. But i think i have to unserialize them? 

This is my code

`@foreach(\App\Models\ImageGallery::All() as $img)
        <p>{{ $img->title }}</p>
        @foreach(\App\Models\Upload::where('id', $img->images)->get() as $image)
          <p>{{ $image->path() }}</p>
        @endforeach
        <p>{{ $img->images }}</p>
@endforeach`

the p is just for showing before i code the rest. It's showing the image upload id's on $img->images.

**Comment by gdbhosale** [comment]
@JerryKrakel,

Please check detailed documentation on
http://laraadmin.com/docs/1.0/uploads_manager#file-access-methods

i hope this will help you well.

Best Regards,

**Comment by JerryKrakel** [comment]
Yes, i did, i can get the path() of al uploads but not just the path() of the uploads wich are bind to a current id of the module.

Thats kind of the problem im having. the error im getting when im trying to unserialize them is:

unserialize(): Error at offset 0 of 25 bytes

i got 3 fields in the module, title - desc - images. upload 6 images to record1 and 1 to record2.
But i can only get it to show everyhing and not just wich are bind to record

**Comment by gdbhosale** [comment]
Check below:

```
@foreach(\App\Models\ImageGallery::All() as $img)
	<p>{{ $img->title }}</p>
	<?php
	$image_ids = json_decode($img->images);
	?>
	@foreach($image_ids as $img_id)
		<p>{{ Upload::find($img_id)->path() }}</p>
	@endforeach
@endforeach
```

This will work. Files data type store image ids in json array format. Check database values.

Regards,

**Comment by JerryKrakel** [comment]
Ah awesome. Sorry for that ;-)

Thanks alot for the quick response and help! Really nice job u peeps doing!
