### ISSUE TITLE
Table overflow on module listing

### ISSUE THREAD

**Issue by rxstriker** [dwijitsolutions/laraadmin#96]
When a module has lots of fields, the table overflows out of the box.
![clients listing aliartalentos](https://cloud.githubusercontent.com/assets/23050598/20011970/5f02f76c-a2a5-11e6-9549-3a746fd937e2.png)

**Comment by gdbhosale** [comment]
@rxstriker 

It is not a problem. We made it like that. We shouldnt have too many columns in table.
You can customise columns from your Controller:
```
public $listing_cols = ['id', 'name'];
```

If you want you are free to change css working as well.

Regards,
