### ISSUE TITLE
Change Module name

### ISSUE THREAD

**Issue by rxstriker** [dwijitsolutions/laraadmin#97]
Is it possible to change a modules name without manually changing all files and tables associated?

**Comment by gdbhosale** [comment]
As of now 'NO'.

As changing every code reference by program is difficult.
For example change of controller name will cause routes to change.
We cannot make such change programmatically.

Regards,

**Comment by rxstriker** [comment]
But you can change the displayed name of a module right?
What if instead of displaying "reports" I want it to display "relatórios"?
I can change the column "name" in the "modules" table in the db, right?
Will it affect in functions?

**Comment by gdbhosale** [comment]
I think you are right...

We should allow user to give "Module display name" and "Module icon as well.

**Comment by gdbhosale** [comment]
Done !!!
