### ISSUE TITLE
unable to type password in cmd 

### ISSUE THREAD

**Issue by azarzaza** [dwijitsolutions/laraadmin#98]
i have install laraadmin everything is install fine when super admin creation i am unable to enter the password when i leave it blank i am unable to login to laraadmin panel

**Comment by slozano95** [comment]
@azarzaza password is not shown in GUI but the installer gets it correctly

**Comment by azarzaza** [comment]
How i login to admin panel

**Comment by slozano95** [comment]
@azarzaza yourdomain.com/admin

**Comment by azarzaza** [comment]
Yeah it k when using the cmd composer la: install it ask env setting the
ask super admin user name and password when asking password I can't enter
the password once I leave it blank in the db there some default value
inserted when login with password unable to login

**Comment by azarzaza** [comment]
Y should the cmd prompt doesn't  allow to enter password then how will I
login to the panel

**Comment by azarzaza** [comment]
I got it and learned  how to configure
