### ISSUE TITLE
Adding manualy row to module_fields table

### ISSUE THREAD

**Issue by netinteractive** [dwijitsolutions/laraadmin#99]
Hi, congrats great work. Here issue that I found :

When I manually add row to module_fields table (I add description field), and make Update Migrations, Update Module - table is not created on database in module table.

**Comment by gdbhosale** [comment]
This wont work as when you can create a field through Module Manager then only field is created in table not after 'Update Module'
`Check https://github.com/dwijitsolutions/laraadmin/blob/master/src/Controllers/FieldController.php:48`
```
	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		$module = Module::find($request->module_id);
		$module_id = $request->module_id;
		
		$field_id = ModuleFields::createField($request);
		
		// Give Default Full Access to Super Admin
		$role = \App\Role::where("name", "SUPER_ADMIN")->first();
		Module::setDefaultFieldRoleAccess($field_id, $role->id, "full");
		
		return redirect()->route(config('laraadmin.adminRoute') . '.modules.show', [$module_id]);
	}
```
